@startuml mitm
scale 8
!theme vibrant
participant "TLS Trust Store" as store
participant curl as app
participant mitmproxy as mitm
participant fourtheorem.com as server

app -> mitm: Hello
mitm -> app: Here's my self signed TLS certificate
app --> store: Is this self signed certificate legit?
store --> app: No!
@enduml
